Update choosing-msal-dotnet.md
MicrosoftDocs/microsoft-authentication-library-dotnet pull request #100
Opened 2023-05-27 17:16 UTC by gladjohn

Update choosing-msal-dotnet.md

2023-05-29 22:07 UTC, jmprieur approved these changes
LGTM. Thanks @gladjohn 
I've added a suggestion

2023-05-29 22:07 UTC, jmprieur commented on msal-dotnet-articles/getting-started/choosing-msal-dotnet.md
> +You are building a SDK for confidential client applications and want to use MSAL.NET low level APIs. In MSAL.NET, an in-memory token cache is provided by default, however, in the case of web apps or
the contracted forms (You're, It's) are recommended in Microsoft Learn

2023-05-29 22:07 UTC, jmprieur commented on msal-dotnet-articles/getting-started/choosing-msal-dotnet.md
> +    instance certificates from Key Vault, or workload identity federation with [Azure Kubernetes Service (AKS)](https://azure.microsoft.com/products/kubernetes-service) and [Managed Identities](https
```suggestion
    instance certificates from Key Vault, or [workload identity federation](https://learn.microsoft.com/azure/active-directory/workload-identities/workload-identity-federation) with [Azure Kubernetes Service (AKS)](https://azure.microsoft.com/products/kubernetes-service) and [Managed Identities](https://learn.microsoft.com/azure/active-directory/managed-identities-azure-resources/overview))
```

2023-05-30 20:38 UTC, pmaytak approved these changes

2023-05-30 23:29 UTC, localden requested changes

2023-05-30 23:29 UTC, localden commented on msal-dotnet-articles/getting-started/choosing-msal-dotnet.md
> +    instance certificates from Key Vault, or [workload identity federation](https://learn.microsoft.com/azure/active-directory/workload-identities/workload-identity-federation) with [Azure Kubernetes
```suggestion
instance certificates from Key Vault, or [workload identity federation](/azure/active-directory/workload-identities/workload-identity-federation) with [Azure Kubernetes Service (AKS)](https://azure.microsoft.com/products/kubernetes-service) and [Managed Identities](/azure/active-directory/managed-identities-azure-resources/overview))
```

2023-05-31 17:30 UTC, gladjohn commented
@localden I am not seeing the change you requested for

2023-06-02 19:44 UTC, merged