Update managed-identity.md
MicrosoftDocs/microsoft-authentication-library-dotnet pull request #108
Opened 2023-05-30 14:02 UTC by bgavrilMS

2023-05-30 14:03 UTC, bgavrilMS commented on msal-dotnet-articles/advanced/managed-identity.md
> +>[Microsoft.Identity.Web](https://github.com/AzureAD/microsoft-identity-web) is a higher level API that offers integration with ASP.NET Core and ASP.NET Classic. Internally it uses MSAL.
CC @jmprieur to update this, I am not sure how to use ID.Web with MI

2023-05-30 17:50 UTC, localden requested changes

2023-05-30 17:50 UTC, localden commented on msal-dotnet-articles/advanced/managed-identity.md
> +Both MSAL.NET and [Azure SDK](https://learn.microsoft.com/dotnet/api/overview/azure/identity-readme?view=azure-dotnet&preserve-view=true) allow to acquire tokens via Managed Identity. Internally, Azu
```suggestion
Both MSAL.NET and [Azure SDK](/dotnet/api/overview/azure/identity-readme?view=azure-dotnet&preserve-view=true) allow to acquire tokens via Managed Identity. Internally, Azure SDK uses MSAL.NET, and it provides a higher-level API via its `DefaultAzureCredential` and `ManagedIdentityCredential` abstractions. 
```

2023-05-30 17:50 UTC, localden commented on msal-dotnet-articles/advanced/managed-identity.md
> +MSAL libraries provide lower level APIs that are closer to the OAuth2 / OIDC protocols.
```suggestion
MSAL libraries provide lower level APIs that are closer to the OAuth2 and OIDC protocols. 
```

2023-05-30 17:50 UTC, localden commented on msal-dotnet-articles/advanced/managed-identity.md
> +>[Microsoft.Identity.Web](https://github.com/AzureAD/microsoft-identity-web) is a higher level API that offers integration with ASP.NET Core and ASP.NET Classic. It supports Managed Identity as well.
```suggestion
[Microsoft.Identity.Web](https://github.com/AzureAD/microsoft-identity-web) is a higher-level API that offers integration with ASP.NET Core and ASP.NET Classic, while using MSAL under the hood. The library also supports Managed Identity.
```

2023-05-30 20:52 UTC, pmaytak approved these changes

2023-05-30 20:52 UTC, pmaytak commented on msal-dotnet-articles/advanced/managed-identity.md
> +Both MSAL.NET and [Azure SDK](https://learn.microsoft.com/dotnet/api/overview/azure/identity-readme?view=azure-dotnet&preserve-view=true) allow to acquire tokens via Managed Identity. Internally, Azu
```suggestion
Both MSAL.NET and [Azure SDK](https://learn.microsoft.com/dotnet/api/overview/azure/identity-readme?view=azure-dotnet&preserve-view=true) allow to acquire tokens via managed identity. Internally, Azure SDK uses MSAL.NET, and it provides a higher level API via its `DefaultAzureCredential` and `ManagedIdentityCredential` abstractions. 
```

2023-05-30 20:52 UTC, pmaytak commented on msal-dotnet-articles/advanced/managed-identity.md
> +If your application already uses one of the SDKs, continue using the same SDK. If you are writing a new application, use Azure SDK if you plan to call other Azure resources, as the SDK integrates bet
```suggestion
If your application already uses one of the SDKs, continue using the same SDK. Use Azure SDK, if you are writing a new application and plan to call other Azure resources, as this SDK provides a better developer experience by allowing the app to run on private developer machines where managed identity doesn't exist. Consider using MSAL if you need to call other downstream web APIs like Microsoft Graph or your own web API. 
```

2023-05-30 22:12 UTC, localden commented
@pmaytak could you please update your suggestions based on latest commits?

2023-05-30 22:34 UTC, pmaytak commented on msal-dotnet-articles/advanced/managed-identity.md
> +Both MSAL.NET and [Azure SDK](/dotnet/api/overview/azure/identity-readme?view=azure-dotnet&preserve-view=true) allow to acquire tokens via Managed Identity. Internally, Azure SDK uses MSAL.NET, and i
```suggestion
Both MSAL.NET and [Azure SDK](/dotnet/api/overview/azure/identity-readme?view=azure-dotnet&preserve-view=true) allow to acquire tokens via managed identity. Internally, Azure SDK uses MSAL.NET, and it provides a higher-level API via its `DefaultAzureCredential` and `ManagedIdentityCredential` abstractions. 
```

2023-05-30 22:35 UTC, pmaytak commented on msal-dotnet-articles/advanced/managed-identity.md
> +[Microsoft.Identity.Web](https://github.com/AzureAD/microsoft-identity-web) is a higher-level API that offers integration with ASP.NET Core and ASP.NET Classic, while using MSAL under the hood. The l
```suggestion
[Microsoft.Identity.Web](https://github.com/AzureAD/microsoft-identity-web) is a higher-level API that offers integration with ASP.NET Core and ASP.NET Classic, while using MSAL under the hood. The library also supports token acquisition with managed identity.
```

2023-06-02 19:43 UTC, localden commented
@jmprieur is the `Microsoft.Identity.Web.ITokenAcquisition.ReplyForbiddenWithWwwAuthenticateHeader` entity really gone from the package?

2023-06-07 01:17 UTC, localden approved these changes

2023-06-07 01:17 UTC, localden approved these changes

2023-06-07 01:17 UTC, localden submitted a review, later dismissed

2023-06-07 04:38 UTC, localden commented
@bgavrilMS updated. Should be going into `main` now.

2023-06-07 04:41 UTC, localden approved these changes

2023-06-07 16:30 UTC, jmprieur commented on msal-dotnet-articles/advanced/managed-identity.md
> +[Microsoft.Identity.Web](https://github.com/AzureAD/microsoft-identity-web) is a higher-level API that offers integration with ASP.NET Core and ASP.NET Classic, while using MSAL under the hood. The l
```suggestion
[Microsoft.Identity.Web](https://github.com/AzureAD/microsoft-identity-web) is a higher-level API that offers integration with ASP.NET Core and ASP.NET Classic, while using MSAL under the hood. The library also provides a way to load credentials (certificates, signed assertions) used by MSAL.NET as client credentials. For certificates it uses the `DefaultAzureCredentials` to fetch certificates from KeyVault. It also offers workload identity federation with managed identity credentials. For details see [CredentialDescription](/dotnet/api/microsoft.identity.abstractions.credentialdescription.keyvaulturl?view=msal-model-dotnet-latest#microsoft-identity-abstractions-credentialdescription-keyvaulturl&preserve-view=true)
```

2023-06-07 16:32 UTC, jmprieur commented
> @jmprieur is the `Microsoft.Identity.Web.ITokenAcquisition.ReplyForbiddenWithWwwAuthenticateHeader` entity really gone from the package?

It should still be there, @localden, but in the Ms.Id.Web.TokenAcquisition NuGet package (since v2.0)

2023-06-07 22:43 UTC, merged