Update proof-of-possession-tokens.md
MicrosoftDocs/microsoft-authentication-library-dotnet pull request #450
Opened 2024-06-18 09:33 UTC by bgavrilMS

2024-06-20 09:47 UTC, bgavrilMS commented
Gentle ping on this @neha-bhargava @trwalke @localden @gladjohn

2024-06-20 17:28 UTC, localden requested changes

2024-06-20 17:28 UTC, localden commented on msal-dotnet-articles/advanced/proof-of-possession-tokens.md
> +- **PoP via Signed HTTP Request (SHR)** . See [PoP key distribution](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-pop-key-distribution-07) and [SHR](https://datatracker.ietf.org/doc/html/dr
```suggestion
- **PoP via Signed HTTP Request (SHR)** . See [PoP key distribution](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-pop-key-distribution-07) and [SHR](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-signed-http-request-03) for the detailed specifications. This is fully supported by Entra ID and by the SDKs for public client scenarios, such as desktop and mobile applications.
```

2024-06-20 17:28 UTC, localden commented on msal-dotnet-articles/advanced/proof-of-possession-tokens.md
> +- **PoP via mutual TLS (mTLS)**. See [RFC 8705](https://datatracker.ietf.org/doc/html/rfc8705) for details. Investigated for confidential clients, i.e. web sites, web apis, server to server calls. No
```suggestion
- **PoP via mutual TLS (mTLS)**. See [RFC 8705](https://datatracker.ietf.org/doc/html/rfc8705) for details. No support exists currently, with the MSAL team assessing the possibility of adding this capability for service-to-service scenarios, such as web applications and web APIs.
```

2024-06-24 15:45 UTC, localden approved these changes

2024-06-24 16:01 UTC, merged